repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        name: 'mypy tgbot'
        files: 'rediskasgu-tgbot/.*\.py'
        args: [--strict]
      - id: mypy
        name: 'mypy backend'
        files: 'rediskasgu-backend/.*\.py'
        args: [--strict]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        name: 'ruff tgbot'
        files: 'rediskasgu-tgbot/.*\.py'
        args: ['--config=ruff.toml']
      - id: ruff
        name: 'ruff backend'
        files: 'rediskasgu-backend/.*\.py'
        args: ['--config=ruff.toml']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff-format
        name: 'ruff-format tgbot'
        files: 'rediskasgu-tgbot/.*\.py'
        args: ['--config=ruff.toml']
      - id: ruff-format
        name: 'ruff-format backend'
        files: 'rediskasgu-tgbot/.*\.py'
        args: ['--config=ruff.toml']

